# Generated by Django 3.2 on 2022-02-25 03:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CharacteristicTestLab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lab', models.CharField(choices=[('None', 'Escoja el Laboratorio'), ('RPG', 'Grupo RPG SAC'), ('DINATEST', 'Grupo DINATEST SAC'), ('TDM', 'Grupo TDM SAC')], default='None', max_length=8)),
                ('matrix', models.CharField(choices=[('None', 'Escoje la Matriz de tipo de ensayos'), ('MS', 'Ensayos de Mecánica de Suelos'), ('VAR', 'Escavación - Resanes - Transportes - Varios'), ('EMS', 'Estudio de Mecánica de Suelos para Cimentaciones, Canales Tuberías y Pavimentos'), ('AG', 'Ensayos para Agregados y Caracterización'), ('MEZCLA', 'Diseños de Mezclas'), ('CONC', 'Ensayos para Concreto de Cemento Portland'), ('PAV', 'Ensayos para Pavimentos')], default='None', max_length=6)),
            ],
            options={
                'verbose_name': 'characteristic_test_labs',
                'verbose_name_plural': 'characteristic_test_labs',
            },
        ),
        migrations.CreateModel(
            name='TestLab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_test', models.CharField(max_length=254)),
                ('basic_norm', models.CharField(blank=True, max_length=254, null=True)),
                ('refer_norm', models.CharField(blank=True, max_length=254, null=True)),
                ('unit', models.CharField(choices=[('None', 'Escoja la unidad'), ('UND', 'Und.'), ('NOCHE', 'noche'), ('DIA', 'día'), ('PROBETA', 'probeta')], default='None', max_length=10)),
                ('quantity', models.PositiveSmallIntegerField(default=1)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('is_parent', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('characteristic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='characteristics', to='tests_labs.characteristictestlab', verbose_name='test caracteristic')),
            ],
            options={
                'verbose_name': 'test_lab',
                'verbose_name_plural': 'tests_labs',
                'ordering': ('created',),
            },
        ),
        migrations.CreateModel(
            name='TestInclude',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_test', to='tests_labs.testlab')),
                ('to_test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_test', to='tests_labs.testlab')),
            ],
        ),
    ]
