# Generated by Django 3.2 on 2022-03-15 21:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tests_labs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testlab',
            name='characteristic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tests_labs.characteristictestlab', verbose_name='test caracteristic'),
        ),
    ]
