# Generated by Django 3.2 on 2022-04-01 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests_labs', '0003_alter_testlab_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testlab',
            name='unit',
            field=models.CharField(choices=[('None', '--------'), ('UND', 'und.'), ('NOCHE', 'noche'), ('DIA', 'día'), ('PROBETA', 'probeta'), ('PUNTO', 'punto'), ('KM/CARRIL', 'km/carril'), ('KM', 'km')], default='None', max_length=10),
        ),
    ]
