# Generated by Django 3.2 on 2022-03-24 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_auto_20220302_1544'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clientprofile',
            options={'ordering': ('-created',), 'verbose_name': 'client profile', 'verbose_name_plural': 'client profiles'},
        ),
        migrations.AlterField(
            model_name='user',
            name='dni',
            field=models.BigIntegerField(blank=True, default=None, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='profession',
            field=models.CharField(choices=[('None', 'Escoje la Profesión'), ('ING', 'Ingeníero'), ('TEC', 'Técnico'), ('ARQ', 'Arquitecto'), ('OPE', 'Operario'), ('SR_a', 'Señor(a)')], default='None', max_length=4),
        ),
    ]
