from django.db import models


class TypeService(models.TextChoices):
    TEST = "TEST", "Ensayo"
    SOIL_MECHANICS_STUDY = "SOIL_MECHANICS_STUDY", "Estudio de Mecánica de Suelos"
    GEOTECHNICS_STYDY = "GEOTECHNICS_STYDY", "Estudio de Geotécnico"


class TypeResponsible(models.TextChoices):
    NONE = None, "N/A"
    CLIENT = "CLIENT", "Cliente"
    LABORATORY = "LABORATORY", "Laboratorio"


class TypeLegalRequirements(models.TextChoices):
    MCSPMTCP = (
        "MCSPMTCP",
        "MANUAL DE CARRETERAS: SUELOS Y PAVIMENTOS DEL MINISTERIO DE TRANSPORTES Y COMUNICACIONES DEL PERÚ",
    )
    N_E050_RNE = "N_E050_RNE", "NORMA E050 DEL REGLAMENTO NACIONAL DE EDIFICACIONES"
    N_CE010_RNE = "N_CE010_RNE", "NORMA CE010 DEL REGLAMENTO NACIONAL DE EDIFICACIONES"
    N_E060_RNE = "N_E060_RNE", "NORMA E060 DEL REGLAMENTO NACIONAL DE EDIFICACIONES"
    ETGCC_EG2013 = (
        "ETGCC_EG2013",
        "ESPECIFICACIONES TÉCNICAS GENERALES PARA CONSTRUCCIÓN DE CARRERAS EG 2013",
    )
    NO_INDICA = "NO_INDICA", "NO INDICA"
    OTROS_ESPECIFIQUE = "OTROS_ESPECIFIQUE", "OTROS ESPECIFIQUE"


class YesNoUnknown(models.TextChoices):
    NA = "N/A", "N/A"
    TRUE = "SI", "SI"
    FALSE = "NO", "NO"
