# Generated by Django 3.2 on 2021-12-23 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('social_reason', models.CharField(max_length=254, verbose_name='razón social')),
                ('address', models.CharField(max_length=254, verbose_name='dirección')),
                ('ruc', models.CharField(max_length=254, verbose_name='RUC')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='actualizado')),
            ],
            options={
                'verbose_name': 'company',
                'verbose_name_plural': 'companies',
                'ordering': ('-created',),
            },
        ),
    ]
