# Generated by Django 3.2 on 2021-12-12 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'ordering': ('-created',), 'verbose_name': 'company', 'verbose_name_plural': 'companies'},
        ),
        migrations.AlterField(
            model_name='company',
            name='RUC',
            field=models.CharField(max_length=254, unique=True),
        ),
    ]
