# Generated by Django 3.2 on 2021-12-25 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='address',
            field=models.CharField(max_length=254),
        ),
        migrations.AlterField(
            model_name='company',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created at'),
        ),
        migrations.AlterField(
            model_name='company',
            name='ruc',
            field=models.CharField(max_length=254),
        ),
        migrations.AlterField(
            model_name='company',
            name='social_reason',
            field=models.CharField(max_length=254),
        ),
        migrations.AlterField(
            model_name='company',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='updated at'),
        ),
    ]
