# Generated by Django 3.2 on 2021-12-12 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_auto_20211212_1212'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='RUC',
            new_name='ruc',
        ),
    ]
