# Generated by Django 3.2 on 2021-12-27 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_auto_20211225_1306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='ruc',
            field=models.BigIntegerField(),
        ),
    ]
