# Generated by Django 3.2 on 2021-12-27 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_alter_company_ruc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='ruc',
            field=models.PositiveBigIntegerField(),
        ),
    ]
