# Generated by Django 3.2 on 2021-12-12 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_rename_ruc_company_ruc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='ruc',
            field=models.CharField(max_length=254),
        ),
    ]
