# Generated by Django 3.2 on 2021-12-28 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_alter_company_ruc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='ruc',
            field=models.PositiveBigIntegerField(unique=True),
        ),
    ]
