# Generated by Django 3.2 on 2022-03-02 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='type_company',
            field=models.CharField(choices=[('INTER', 'Interno'), ('STATE_ENTITY', 'Entidad del Estado'), ('ENTERPRICE', 'Empresa'), ('NATURAL_PERSON', 'Persona Natural')], default='ENTERPRICE', max_length=20),
        ),
    ]
