# Generated by Django 3.2 on 2022-03-02 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='type_service',
            field=models.CharField(choices=[('TEST', 'Ensayo'), ('SOIL_MECHANICS_STUDY', 'Estudio de Mecánica de Suelos'), ('GEOTECHNICS_STYDY', 'Estudio de Geotécnico')], default='TEST', max_length=20),
        ),
    ]
