# Generated by Django 3.2 on 2022-03-02 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_auto_20220302_1544'),
        ('orders', '0002_order_type_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('responsible', models.CharField(choices=[('None', 'N/A'), ('CLIENT', 'Cliente'), ('LABORATORY', 'Laboratorio')], default='CLIENT', max_length=15)),
                ('riic', models.TextField(blank=True, default='NO SE TIENEN REQUISITOS PARA EL INGRESO', help_text='Información aplicable solo cuando el muestreo es responsabilidad del laboratorio', null=True)),
                ('remseg', models.TextField(blank=True, null=True)),
                ('rlras', models.CharField(choices=[('MCSPMTCP', 'MANUAL DE CARRETERAS: SUELOS Y PAVIMENTOS DEL MINISTERIO DE TRANSPORTES Y COMUNICACIONES DEL PERÚ'), ('N_E050_RNE', 'NORMA E050 DEL REGLAMENTO NACIONAL DE EDIFICACIONES'), ('N_CE010_RNE', 'NORMA CE010 DEL REGLAMENTO NACIONAL DE EDIFICACIONES'), ('N_E060_RNE', 'NORMA E060 DEL REGLAMENTO NACIONAL DE EDIFICACIONES'), ('ETGCC_EG2013', 'ESPECIFICACIONES TÉCNICAS GENERALES PARA CONSTRUCCIÓN DE CARRERAS EG 2013'), ('NO_INDICA', 'NO INDICA'), ('OTROS_ESPECIFIQUE', 'OTROS ESPECIFIQUE')], default='NO_INDICA', max_length=20)),
                ('observation', models.TextField(blank=True, null=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='order_info', to='orders.order')),
                ('recl', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recl_orderinfo', to='members.adminprofile', verbose_name='rirs_name_order_info')),
                ('rirs', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rirs_orderinfo', to='members.adminprofile', verbose_name='rirs_name_order_info')),
            ],
        ),
    ]
