# Generated by Django 3.2 on 2022-03-02 18:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_auto_20220302_1544'),
        ('orders', '0003_orderinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderinfo',
            name='recl',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recl_orderinfo', to='members.adminprofile', verbose_name='recl_orderinfo'),
        ),
        migrations.AlterField(
            model_name='orderinfo',
            name='rirs',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rirs_orderinfo', to='members.adminprofile', verbose_name='rirs_order_info'),
        ),
    ]
