# Generated by Django 3.2 on 2022-03-03 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20220302_1819'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='number_request',
        ),
    ]
