# Generated by Django 3.2 on 2022-03-15 13:30

from django.db import migrations
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_auto_20220302_1544'),
        ('projects', '0001_initial'),
        ('orders', '0005_remove_order_number_request'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='client',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field='company', chained_model_field='company', null=True, on_delete=django.db.models.deletion.SET_NULL, to='members.clientprofile', verbose_name='client_order'),
        ),
        migrations.AlterField(
            model_name='order',
            name='project',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field='company', chained_model_field='company', null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.project', verbose_name='project_order'),
        ),
    ]
