# Generated by Django 3.2 on 2022-03-15 21:29

from django.db import migrations
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('tests_labs', '0001_initial'),
        ('orders', '0006_auto_20220315_0830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitems',
            name='test_lab',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field='characteristic', chained_model_field='characteristic', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='test_lab_items', to='tests_labs.testlab', verbose_name='test lab'),
        ),
    ]
