# Generated by Django 3.2 on 2022-03-15 22:40

from django.db import migrations
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('tests_labs', '0002_alter_testlab_characteristic'),
        ('orders', '0009_alter_orderitems_test_lab'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitems',
            name='test_lab',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field='characteristictestlab', chained_model_field='characteristictestlab', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='test_lab_items', to='tests_labs.testlab', verbose_name='test lab'),
        ),
    ]
