# Generated by Django 3.2 on 2022-03-17 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests_labs', '0002_alter_testlab_characteristic'),
        ('orders', '0015_auto_20220317_1313'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrderItems',
            new_name='OrderItem',
        ),
    ]
