# Generated by Django 3.2 on 2022-03-17 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0016_rename_orderitems_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='obs',
            field=models.TextField(blank=True, null=True),
        ),
    ]
