# Generated by Django 3.2 on 2022-03-25 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0021_orderitemexecution'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='requirement',
            field=models.BooleanField(default=True),
        ),
    ]
