# Generated by Django 3.2 on 2022-03-26 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0024_auto_20220326_1554'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='number_execution',
            field=models.BigIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='number_liquidation',
            field=models.BigIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='number_quatotion',
            field=models.BigIntegerField(blank=True, default=0, null=True),
        ),
    ]
