# Generated by Django 3.2 on 2022-03-27 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0028_auto_20220327_0223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='orderinfo',
            field=models.ManyToManyField(blank=True, null=True, to='orders.OrderInfo', verbose_name='questions'),
        ),
    ]
