# Generated by Django 3.2 on 2022-03-27 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0032_auto_20220327_1053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderinfo',
            name='question_1',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='orderinfo',
            name='question_2',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='orderinfo',
            name='question_3',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='orderinfo',
            name='question_4',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='orderinfo',
            name='question_5',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='orderinfo',
            name='question_6',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='orderinfo',
            name='question_7',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='orderinfo',
            name='question_8',
            field=models.BooleanField(default=True),
        ),
    ]
