# Generated by Django 3.2 on 2022-04-01 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0034_auto_20220401_1311'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderquatition',
            name='created_execution',
        ),
        migrations.RemoveField(
            model_name='orderquatition',
            name='created_liquidation',
        ),
        migrations.RemoveField(
            model_name='orderquatition',
            name='created_quatotion',
        ),
        migrations.RemoveField(
            model_name='orderquatition',
            name='number_execution',
        ),
        migrations.RemoveField(
            model_name='orderquatition',
            name='number_liquidation',
        ),
        migrations.RemoveField(
            model_name='orderquatition',
            name='number_quatotion',
        ),
    ]
