# Generated by Django 3.2 on 2022-04-03 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0037_auto_20220401_2356'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderinfo',
            old_name='order',
            new_name='order_quotation',
        ),
        migrations.AlterField(
            model_name='orderitemquatotion',
            name='sampling_by',
            field=models.BooleanField(choices=[('None', 'N/A'), ('True', 'SI'), ('False', 'NO')], default='True', null=True),
        ),
    ]
