# Generated by Django 3.2 on 2022-04-03 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0038_auto_20220403_1107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitemquatotion',
            name='sampling_by',
            field=models.CharField(choices=[('N/A', 'N/A'), ('SI', 'SI'), ('NO', 'NO')], default='SI', max_length=3),
        ),
    ]
