# Generated by Django 3.2 on 2022-04-04 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0041_auto_20220403_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitemexecution',
            name='sampling_by',
            field=models.CharField(choices=[('N/A', 'N/A'), ('SI', 'SI'), ('NO', 'NO')], default='SI', max_length=4),
        ),
    ]
