# Generated by Django 3.2 on 2022-04-04 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0042_alter_orderitemexecution_sampling_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderexecution',
            name='observation',
            field=models.TextField(blank=True, null=True),
        ),
    ]
