# Generated by Django 3.2 on 2022-04-04 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0043_orderexecution_observation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderliquidation',
            name='order_execution',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='orders.orderexecution'),
        ),
    ]
