# Generated by Django 3.2 on 2022-04-04 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0045_auto_20220404_0815'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderliquidation',
            name='observation',
            field=models.TextField(blank=True, null=True),
        ),
    ]
