# Generated by Django 3.2 on 2022-04-09 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0046_orderliquidation_observation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderinfo',
            name='order_quotation',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.orderquatotion'),
        ),
    ]
