# Generated by Django 3.2 on 2022-01-16 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestLab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matrix', models.CharField(choices=[('None', 'Escoje la Matriz de tipo de ensayos'), ('MS', 'Ensayos de Mecánica de Suelos'), ('VAR', 'Escavación - Resanes - Transportes - Varios'), ('EMS', 'Estudio de Mecánica de Suelos para Cimentaciones, Canales Tuberías y Pavimentos'), ('AG', 'Ensayos para Agregados y Caracterización'), ('MEZCLA', 'Diseños de Mezclas'), ('CONC', 'Ensayos para Concreto de Cemento Portland'), ('PAV', 'Ensayos para Pavimentos')], default='None', max_length=6)),
                ('lab', models.CharField(choices=[('None', 'Escoja el Laboratorio'), ('RPG', 'Grupo RPG SAC'), ('DINATEST', 'Grupo DINATEST SAC'), ('TDM', 'Grupo TDM SAC')], default='None', max_length=8)),
                ('name_test', models.CharField(max_length=254)),
                ('basic_norm', models.CharField(blank=True, max_length=254, null=True)),
                ('refer_norm', models.CharField(blank=True, max_length=254, null=True)),
                ('unit', models.CharField(choices=[('None', 'Escoja la unidad'), ('UND', 'Und.'), ('NOCHE', 'noche'), ('DIA', 'día'), ('PROBETA', 'probeta')], default='None', max_length=10)),
                ('quantity', models.PositiveSmallIntegerField(default=1)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('child', models.ManyToManyField(blank=True, default=None, to='tests_labs.TestLab')),
            ],
            options={
                'verbose_name': 'test_lab',
                'verbose_name_plural': 'tests_labs',
                'ordering': ('created',),
            },
        ),
    ]
