# Generated by Django 3.2 on 2022-01-19 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests_labs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testlab',
            name='child',
        ),
        migrations.AddField(
            model_name='testlab',
            name='child_tests',
            field=models.ManyToManyField(blank=True, default=None, to='tests_labs.TestLab', verbose_name='list of child tests'),
        ),
    ]
