# Generated by Django 3.2 on 2022-01-19 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests_labs', '0002_auto_20220118_2104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testlab',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
    ]
