# Generated by Django 3.2 on 2022-01-20 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests_labs', '0008_testlab_is_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testlab',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='testlab',
            name='quantity',
            field=models.PositiveSmallIntegerField(blank=True, default=1, null=True),
        ),
    ]
