# Generated by Django 3.2 on 2022-01-21 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests_labs', '0009_auto_20220120_1007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testlab',
            name='child_tests',
            field=models.ManyToManyField(blank=True, default=None, related_name='_tests_labs_testlab_child_tests_+', to='tests_labs.TestLab', verbose_name='list of child tests'),
        ),
    ]
