# Generated by Django 3.2 on 2022-01-21 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests_labs', '0010_alter_testlab_child_tests'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testlab',
            name='child_tests',
            field=models.ManyToManyField(blank=True, default=None, to='tests_labs.TestLab', verbose_name='list of child tests'),
        ),
    ]
