# Generated by Django 3.2 on 2022-01-21 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tests_labs', '0011_alter_testlab_child_tests'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testlab',
            options={'verbose_name': 'test_lab', 'verbose_name_plural': 'tests_labs'},
        ),
        migrations.RemoveField(
            model_name='testlab',
            name='child_tests',
        ),
        migrations.RemoveField(
            model_name='testlab',
            name='created',
        ),
        migrations.RemoveField(
            model_name='testlab',
            name='is_parent',
        ),
        migrations.RemoveField(
            model_name='testlab',
            name='lab',
        ),
        migrations.RemoveField(
            model_name='testlab',
            name='matrix',
        ),
        migrations.RemoveField(
            model_name='testlab',
            name='updated',
        ),
        migrations.AlterField(
            model_name='testlab',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='testlab',
            name='quantity',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.CreateModel(
            name='CharacteristicTestLab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matrix', models.CharField(choices=[('None', 'Escoje la Matriz de tipo de ensayos'), ('MS', 'Ensayos de Mecánica de Suelos'), ('VAR', 'Escavación - Resanes - Transportes - Varios'), ('EMS', 'Estudio de Mecánica de Suelos para Cimentaciones, Canales Tuberías y Pavimentos'), ('AG', 'Ensayos para Agregados y Caracterización'), ('MEZCLA', 'Diseños de Mezclas'), ('CONC', 'Ensayos para Concreto de Cemento Portland'), ('PAV', 'Ensayos para Pavimentos')], default='None', max_length=6)),
                ('lab', models.CharField(choices=[('None', 'Escoja el Laboratorio'), ('RPG', 'Grupo RPG SAC'), ('DINATEST', 'Grupo DINATEST SAC'), ('TDM', 'Grupo TDM SAC')], default='None', max_length=8)),
                ('is_child', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('child_tests', models.ManyToManyField(blank=True, to='tests_labs.CharacteristicTestLab', verbose_name='list of child tests')),
            ],
            options={
                'verbose_name': 'characteristic_test_labs',
                'verbose_name_plural': 'characteristic_test_labs',
                'ordering': ('created',),
            },
        ),
        migrations.AddField(
            model_name='testlab',
            name='characteristic',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='tests_labs.characteristictestlab', verbose_name='test caracteristics'),
            preserve_default=False,
        ),
    ]
