# Generated by Django 3.2 on 2022-01-22 20:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tests_labs', '0012_auto_20220121_1047'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='characteristictestlab',
            name='child_tests',
        ),
        migrations.RemoveField(
            model_name='characteristictestlab',
            name='is_child',
        ),
        migrations.AddField(
            model_name='testlab',
            name='child_tests',
            field=models.ManyToManyField(blank=True, to='tests_labs.TestLab', verbose_name='child tests'),
        ),
        migrations.AddField(
            model_name='testlab',
            name='is_child',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='testlab',
            name='characteristic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tests_labs.characteristictestlab', verbose_name='test caracteristic'),
        ),
    ]
