# Generated by Django 3.2 on 2022-01-25 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests_labs', '0016_auto_20220125_0800'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TestFriendship',
            new_name='TestInclude',
        ),
    ]
