# Generated by Django 3.2 on 2022-01-25 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tests_labs', '0017_rename_testfriendship_testinclude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testinclude',
            name='from_test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_test', to='tests_labs.testlab'),
        ),
        migrations.AlterField(
            model_name='testinclude',
            name='to_test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_test', to='tests_labs.testlab'),
        ),
    ]
