# Generated by Django 3.2 on 2022-04-04 23:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0046_orderliquidation_observation'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaidItemQuatotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=10)),
                ('order_quatotion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.orderquatotion', verbose_name='paid quatotion')),
            ],
            options={
                'ordering': ('pk',),
            },
        ),
    ]
