# Generated by Django 3.2 on 2022-01-31 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitems',
            name='sampling_by',
        ),
    ]
