# Generated by Django 3.2 on 2022-01-31 23:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_remove_orderitems_sampling_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='number_request',
        ),
    ]
