# Generated by Django 3.2 on 2022-02-01 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_number_request'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='number_request',
            field=models.CharField(default='codigo', max_length=20),
        ),
    ]
