# Generated by Django 3.2 on 2022-02-03 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_order_number_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitems',
            name='sampling_by',
            field=models.BooleanField(null=True),
        ),
    ]
