# Generated by Django 3.2 on 2022-02-05 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_orderitems_sampling_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitems',
            name='quantity',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
