# Generated by Django 3.2 on 2022-02-05 23:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tests_labs', '0020_alter_testlab_characteristic'),
        ('orders', '0007_alter_orderitems_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitems',
            name='characteristictestlab',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='characteristictestlab_items', to='tests_labs.characteristictestlab', verbose_name='characteristictestlab'),
        ),
    ]
