# Generated by Django 3.2 on 2022-02-06 18:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_alter_orderitems_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='state',
            field=models.CharField(choices=[('COST_QUOTATION', 'Cotización'), ('REQUIREMENT', 'Requerimiento'), ('EXECUTION_ORDER', 'Orden de Ejecución'), ('LIQUIDATION', 'Liquidación')], default='COST_QUOTATION', max_length=20),
        ),
        migrations.CreateModel(
            name='OrderExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_order', to='orders.order')),
                ('to_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_order', to='orders.order')),
            ],
        ),
    ]
