# Generated by Django 3.2 on 2022-02-06 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_auto_20220206_1319'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrderExecution',
            new_name='OrderState',
        ),
    ]
