# Generated by Django 3.2 on 2022-02-07 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_order_execution_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='state',
        ),
        migrations.AddField(
            model_name='order',
            name='cost_quatotion',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='order',
            name='liquidation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='requirement',
            field=models.BooleanField(default=False),
        ),
    ]
