# Generated by Django 3.2 on 2022-02-07 18:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
        ('orders', '0014_auto_20220207_0942'),
    ]

    operations = [
        migrations.DeleteModel(
            name='State',
        ),
        migrations.AddField(
            model_name='order',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='companies.company', verbose_name='company_order'),
        ),
    ]
