# Generated by Django 3.2 on 2022-02-08 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0016_order_project'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ('pk',), 'verbose_name': 'order', 'verbose_name_plural': 'orders'},
        ),
        migrations.RemoveField(
            model_name='order',
            name='company',
        ),
        migrations.RemoveField(
            model_name='order',
            name='project',
        ),
        migrations.DeleteModel(
            name='OrderState',
        ),
    ]
