# Generated by Django 3.2 on 2021-12-23 20:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_alter_user_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profession', models.CharField(choices=[('ING', 'Ingeníero'), ('TEC', 'Técnico'), ('SR_a', 'Señor(a)')], default='TEC', max_length=4, verbose_name='profession')),
                ('cell_phone', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='cell phone')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='related admin profile')),
            ],
        ),
    ]
