# Generated by Django 3.2 on 2021-12-24 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_adminprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminprofile',
            name='profession',
            field=models.CharField(choices=[('None', 'Escoje la Profesión'), ('ING', 'Ingeníero'), ('TEC', 'Técnico'), ('SR_a', 'Señor(a)')], default='None', max_length=4, verbose_name='profession'),
        ),
        migrations.AlterField(
            model_name='user',
            name='dni',
            field=models.BigIntegerField(default=None, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('None', 'Escoje el Rol'), ('CLI', 'Cliente'), ('ADM', 'Admin')], default='None', max_length=4),
        ),
    ]
