# Generated by Django 3.2 on 2021-12-24 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_auto_20211223_2145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminprofile',
            name='cell_phone',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='adminprofile',
            name='profession',
            field=models.CharField(choices=[('None', 'Escoje la Profesión'), ('ING', 'Ingeníero'), ('TEC', 'Técnico'), ('SR_a', 'Señor(a)')], default='None', max_length=4),
        ),
    ]
